//import "oaidl.idl";
//import "ocidl.idl";
import "AudioDeviceWatcher.idl";

namespace CppUwpWinRtDeviceWatcherTest01
{
	runtimeclass MainPageViewModel
	{
		MainPageViewModel();

		AudioDeviceWatcher AudioInputs;
		
		//Windows.Devices.Enumeration.DeviceInformation AudioInputDevice{ get; };
		//Windows.Foundation.Collections.IObservableVector<IInspectable> AudioInputDevices{ get; };
	}
}