//import "oaidl.idl";
//import "ocidl.idl";
import "AudioDeviceWatcher.idl";

namespace CppUwpWinRtDeviceWatcherTest01
{
	runtimeclass MainPageViewModel
	{
		MainPageViewModel(Windows.UI.Core.CoreDispatcher dispatcher);

		void OnNavigatedTo(Windows.UI.Xaml.Navigation.NavigationEventArgs e);

		AudioDeviceWatcher AudioInputs{ get; };
		
		//Windows.Devices.Enumeration.DeviceInformation AudioInputDevice{ get; };
		//Windows.Foundation.Collections.IObservableVector<IInspectable> AudioInputDevices{ get; };
	}
}